project:
  type: book
  # pre-render: make quarto-prerender
  output-dir: docs

execute:
  eval: false

book:
  title: "A tutorial for brms"
  sidebar:
    title: "A tutorial for brms"
  chapters:
    - index.qmd
    - getting-started.qmd
    - lin-reg-brms.qmd
    - cooking-w-bayes.qmd
    - tweaking-reg.qmd
    - flex-glms.qmd

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    callout-appearance: simple

bibliography: references.bib