# Getting started with brms

## Installation

Making `brms` work in our computer requires some preparation. First, updating
R to its latest version will help our libraries work better with each other
and with R itself. Installing brms with an older version of R may work, but is
likely to cause problems later.

### C++ toolchain

`brms` uses C++ to translate our models in R into a machinespeak that the
computer runs more efficiently. So, our computer needs a toolchain to run C++
in the background. Setting up this toolchain can take several minutes, but
needs to be done only once.

**In Windows**, the C++ toolchain needs *RTools* 4.5. To check if this is
already installed, go to R and run `devtools::find_rtools()`. To install
RTools, first go to [this website](https://cran.r-project.org/bin/windows/Rtools/rtools45/rtools.html).
Here, find the *Rtools45 installer*, download it, and follow its instructions
while keeping all the default choices.

**In macOS**, the C++ toolchain needs *Xcode Command Line Tools*. To check if
this is already installed, go to the Terminal (open `Finder > Applications >
Terminal`) and run

```
g++ --version
make --version
```

If your mac has `g++` at version 4.9.3 or later and `make` at version
3.81 or later, you do not need to install anything else (although newer
versions of `g++` are faster). If you do not have these tools, or if you want
to update them, run

```
sudo apt install g++
sudo apt install make
```

### Default version of brms

With our C++ toolchain ready, we can go back to R and install `brms`. It may take a few minutes to download and install all the packages bundled with `brms`.

```{r install brms}
#| eval: false
install.packages("brms")
```



### Faster brms with cmdstanr

`brms` uses a backend to interface with Stan. The default backend is `rstan`,
which does not require any additional installation but is somewhat slow. An
alternative backend is `cmdstanr`, which needs to be installed separately but is much faster than `rstan`.
